---
title: "my post"
date: 2019-02-24
---

title: New Page coming soon!
author: Me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  New page coming soon!

# social links
twitter_username: joardar7
github_username:  joardar-aditya

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
